// <auto-generated />
using System;
using BeautyClinic.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautyClinic.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401212721_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BeautyClinic.Core.Models.Appointment.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProcedureRoom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ProcedureId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Clinic.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Clinics", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Consulation.BodyAnamnesis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChosenTreatmentNotes")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MainComplaints")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("MeasurementId");

                    b.ToTable("BodyAnamnesis", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Consulation.FacialAnamnesis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("FacialHairAlterationsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("KeratinizationAlterationsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LiquidContentFormationsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MainComplaints")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("MelaninRelatedPigmentSpotsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("OilinessClassification")
                        .HasColumnType("int");

                    b.Property<int>("SensitivityClassification")
                        .HasColumnType("int");

                    b.Property<bool>("SequelaeOrScarsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SkinClassification")
                        .HasColumnType("int");

                    b.Property<bool>("SkinLesionsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SkinThicknessClassification")
                        .HasColumnType("int");

                    b.Property<bool>("SolidFormationsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("VascularAlterationSpotsPresent")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClinicId");

                    b.ToTable("FacialAnamnesis", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Patient.FemaleHabits", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("AcidsUsed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AlcoholConsumptionFrequency")
                        .HasColumnType("int");

                    b.Property<bool>("BalencedDiet")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Breastfeeding")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("ConsumesAlcoholicBeverage")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int?>("PhysicalActivityDaysPerWeek")
                        .HasColumnType("int");

                    b.Property<bool>("PracticesPhysicalActivities")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Pregnant")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RegularBowels")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RegularContraceptiveUse")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RegularMenstrualCycle")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RegularSleep")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Smoker")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("UseAcidOnSkin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("UsesDailySunscreen")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClinicId");

                    b.ToTable("FemaleHabits", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Patient.Habits", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("AcidsUsed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AlcoholConsumptionFrequency")
                        .HasColumnType("int");

                    b.Property<bool>("BalencedDiet")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("ConsumesAlcoholicBeverage")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PhysicalActivityDaysPerWeek")
                        .HasColumnType("int");

                    b.Property<bool>("PracticesPhysicalActivities")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RegularBowels")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RegularSleep")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Smoker")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("UseAcidOnSkin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("UsesDailySunscreen")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClinicId");

                    b.ToTable("Habits", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Patient.Measurements", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Bust")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Hip")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("LeftArm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("LeftCalf")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("LeftThigh")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("RightArm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RightCalf")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RightThigh")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("UpperAbdomen")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClinicId");

                    b.ToTable("Measurements", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Patient.PatientHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DentalProstheses")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Epilepsy")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HeartProblem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Hypertension")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MetalProstheses")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OncologicalTreatments")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Pacemaker")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PreviousTreatments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("UnderMedicalTreatment")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClinicId");

                    b.ToTable("PatientHistory", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Person.Individual", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ClinicId");

                    b.ToTable("Individual", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Person.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfessionalCouncil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfessionalCouncilState")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("ProfessionalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ClinicId");

                    b.ToTable("Professional", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Procedure.Procedure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConsumedProducts")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentUsed")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Procedure", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Procedure.ProcedurePack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("PackName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SessionsQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("ProcedurePack", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Procedure.ProcedurePackProcedure", b =>
                {
                    b.Property<Guid>("ProcedurePackId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProcedurePackId", "ProcedureId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("ProcedurePackProcedures");
                });

            modelBuilder.Entity("BeautyClinic.Core.ValueObjects.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Appointment.Appointment", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Person.Individual", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Procedure.Procedure", "Procedure")
                        .WithMany("Appointments")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Person.Professional", "Professional")
                        .WithMany("Appointments")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Clinic");

                    b.Navigation("Procedure");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Consulation.BodyAnamnesis", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Person.Individual", "Client")
                        .WithMany("BodyAnamneses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Patient.Measurements", "Measurement")
                        .WithMany("BodyAnamneses")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Clinic");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Consulation.FacialAnamnesis", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Person.Individual", "Client")
                        .WithMany("FacialAnamneses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Patient.FemaleHabits", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Person.Individual", "Client")
                        .WithMany("FemaleHabits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Patient.Habits", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Person.Individual", "Client")
                        .WithMany("Habits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Patient.Measurements", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Person.Individual", "Client")
                        .WithMany("Measurements")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Patient.PatientHistory", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Person.Individual", "Client")
                        .WithMany("PatientHistories")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Person.Individual", b =>
                {
                    b.HasOne("BeautyClinic.Core.ValueObjects.Address", "Address")
                        .WithMany("Individuals")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Person.Professional", b =>
                {
                    b.HasOne("BeautyClinic.Core.ValueObjects.Address", "Address")
                        .WithMany("Professionals")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Procedure.Procedure", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Procedure.ProcedurePack", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Procedure.ProcedurePackProcedure", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Procedure.Procedure", "Procedure")
                        .WithMany("ProcedurePackProcedures")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautyClinic.Core.Models.Procedure.ProcedurePack", "ProcedurePack")
                        .WithMany("ProcedurePackProcedures")
                        .HasForeignKey("ProcedurePackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Procedure");

                    b.Navigation("ProcedurePack");
                });

            modelBuilder.Entity("BeautyClinic.Core.ValueObjects.Address", b =>
                {
                    b.HasOne("BeautyClinic.Core.Models.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Patient.Measurements", b =>
                {
                    b.Navigation("BodyAnamneses");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Person.Individual", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BodyAnamneses");

                    b.Navigation("FacialAnamneses");

                    b.Navigation("FemaleHabits");

                    b.Navigation("Habits");

                    b.Navigation("Measurements");

                    b.Navigation("PatientHistories");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Person.Professional", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Procedure.Procedure", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ProcedurePackProcedures");
                });

            modelBuilder.Entity("BeautyClinic.Core.Models.Procedure.ProcedurePack", b =>
                {
                    b.Navigation("ProcedurePackProcedures");
                });

            modelBuilder.Entity("BeautyClinic.Core.ValueObjects.Address", b =>
                {
                    b.Navigation("Individuals");

                    b.Navigation("Professionals");
                });
#pragma warning restore 612, 618
        }
    }
}
